version: '3.1'
services:
   database:
      image: mysql
      ports:
       - "3306:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=example
       - MYSQL_USER=shah
       - MYSQL_PASSWORD=passwd
       - MYSQL_DATABASE=demodb
   web:
      image: nginx