version: '1.1'
services:
   proxy:
      build:
         context: .
         dockerfile: Dockerfile_nginx
      image: nginx_2
      ports:
       - '80:80'
      volumes:
       - . :/usr/share/nginx/html/
	  